### PR TITLE
Update blockly runtime

### PR DESCRIPTION
**Pull request by jmacentee**
Update key blockly runtime code files from ZIP download https://developers.google.com/blockly/installation/overview to catch any current bug fixes before starting auto-save upgrade.

Since this is my first contribution to someone else's Github OSS, I am trying to do everything in micro-transactions.

### CODE REVIEW

**Comment by bjpirt** [comment]
Crossposting from the Google group:

I had been wondering about implementing a generic saving mechanism that would be the same across all apps (the same UI, but the apps would not be compatible for obvious reasons) so as long as an app implemented methods that serialise and deserialise a program and emit events when it changes, they can all use the same UI.

It might make sense for me to implement that and then work this into it.

What do you think?

**Comment by bjpirt** [comment]
Closing this pull request because it has all been merged in now, although I just found that the updated blockly runtime seems to have stopped things working on touch devices. I reverted that file and now it all seems to work fine. Was there any reason for updating it other than just wanting the most recent version?

**Comment by jmacentee** [comment]
I wasn’t aware that Blockly ever worked on touch devices.  In my testing it had not (iPad).  I’ll have to test again.

I don’t recall specifically, I think I pulled the latest Blockly because Mirobot version was missing some file – I assume the one that dealt with auto-saving the current program in local storage.  If you reverted it and it all works, then I am sure that is fine.

--Jason

**Comment by bjpirt** [comment]
It seems to work fine on my iPad (still running iOS 6, so not very up to date). Give it a shot and let me know if you spot any issues.

**Pull request closed without merging**
